### ISSUE TITLE
My browser isn't loading any of the code I write

### ISSUE THREAD

**Issue by Sophia-Villamayor** [Sophia-Villamayor/svg-smiley-face#1]
@HannahDelaney
I noticed that the code I'm writing isn't showing on my browser. Do you know why that is?

<img width="1650" alt="Screen Shot 2020-10-14 at 10 06 16 AM" src="https://user-images.githubusercontent.com/54897840/96000456-eafc6680-0e04-11eb-855b-c3257fc2440d.png">

**Comment by HannahDelaney** [comment]
The smallest of things!

Your opening `<svg>` tag doesn't have a closing bracket.
Add that and it will appear!

**Comment by Sophia-Villamayor** [comment]
@HannahDelaney Uhhhh, let's just pretend this didn't happen 🙃 This is so embarrassing LOOL
